(ns rules-clj.tidy
  "Writes the BUILD files a Clojure source tree implies.

  A namespace already declares its dependencies — that is what an `ns` form is — so
  restating them in a BUILD file is duplication, and duplication drifts. This reads the
  `ns` forms and writes the targets they imply.

  It reads them with Clojure's own reader rather than a parser of its own. An `ns` form is
  Clojure code, and code is exactly the thing whose grammar a hand-written parser gets
  subtly wrong — reader conditionals, metadata, `#_` discards, string escapes. Reading the
  first form of a file costs nothing and cannot disagree with the compiler.

  Two modes, and the second is the point:

    write   rewrite the BUILD files
    check   fail if they are not what would be written, so a stale one fails CI rather
            than being discovered by the next person"
  (:require [clojure.java.io :as io]
            [clojure.string :as str])
  (:import [java.io File PushbackReader]))

(defn- clojure-file?
  [^File f]
  (and (.isFile f)
       (re-find #"\.clj[cs]?$" (.getName f))))

(defn read-ns-form
  "Returns the `ns` form of a file, or nil if it does not start with one.

  Deliberately tolerant: a file that fails to read is skipped rather than fatal, because a
  source tree being tidied is often a source tree mid-edit, and a generator that refuses to
  run until every file parses is a generator people stop running."
  [^File file]
  (try
    (with-open [reader (PushbackReader. (io/reader file))]
      (binding [*read-eval* false]
        (loop []
          (let [form (read {:eof ::eof :read-cond :allow} reader)]
            (cond
              (= ::eof form) nil
              (and (seq? form) (= 'ns (first form))) form
              :else (recur))))))
    (catch Exception _ nil)))

(defn ns-name-of
  [ns-form]
  (second ns-form))

(defn required-namespaces
  "The namespaces an `ns` form pulls in, from :require and :use."
  [ns-form]
  (->> (drop 2 ns-form)
       (filter seq?)
       (filter #(#{:require :use} (first %)))
       (mapcat rest)
       (keep (fn [spec]
               (cond
                 (symbol? spec) spec
                 (and (sequential? spec) (symbol? (first spec))) (first spec)
                 :else nil)))
       (into (sorted-set))))

(defn- target-of
  [ns-sym]
  (-> (name ns-sym)
      (str/replace "." "_")
      (str/replace "-" "_")))

(defn- test-namespace?
  [ns-sym]
  (str/ends-with? (name ns-sym) "-test"))

(defn- relative
  [^File root ^File file]
  ;; .toString, not .getPath: relativize returns a Path, which has no getPath. The two
  ;; types are easy to mix up and reflection only complains at runtime.
  (str/replace (str (.relativize (.toPath root) (.toPath file))) File/separator "/"))

(defn- source-files
  [^File root]
  (->> (file-seq root) (filter clojure-file?) (sort-by #(.getPath ^File %))))

(defn- render-target
  [{:keys [name' srcs namespaces deps strip-prefix testonly]}]
  (str "clj_library(\n"
       "    name = \"" name' "\",\n"
       (when testonly "    testonly = True,\n")
       "    srcs = [" (str/join ", " (map #(str "\"" % "\"") srcs)) "],\n"
       "    namespaces = [" (str/join ", " (map #(str "\"" % "\"") namespaces)) "],\n"
       "    strip_prefix = \"" strip-prefix "\",\n"
       (when (seq deps)
         (str "    deps = [\n"
              (str/join "" (for [d deps] (str "        \"" d "\",\n")))
              "    ],\n"))
       ")\n"))

(defn- render-test
  [{:keys [name' ns-sym]}]
  ;; `<library>.test` rather than `<library>_test`: a test namespace is usually already
  ;; called something-test, and target names must be unique within a package, so the
  ;; alternative is demo_user_test_test.
  (str "clj_test(\n"
       "    name = \"" name' ".test\",\n"
       "    ns = \"" ns-sym "\",\n"
       "    deps = [\":" name' "\"],\n"
       ")\n"))

(defn build-file-content
  "The BUILD file for one directory of a source root."
  [{:keys [files strip-prefix ns->label]}]
  (let [entries (for [{:keys [file ns-sym requires]} files
                      :let [target (target-of ns-sym)]]
                  {:name' target
                   :ns-sym ns-sym
                   :srcs [(.getName ^File file)]
                   :namespaces [(str ns-sym)]
                   :testonly (test-namespace? ns-sym)
                   :strip-prefix strip-prefix
                   :deps (->> requires
                              (keep ns->label)
                              (into (sorted-set))
                              vec)})
        has-tests? (some (comp test-namespace? :ns-sym) files)]
    (str "# Generated by `bazel run //tools/tidy`. Edit the ns forms, not this file.\n"
         "load(\"@rules_clj//clojure:defs.bzl\", \"clj_library\""
         (when has-tests? ", \"clj_test\"") ")\n\n"
         "package(default_visibility = [\"//visibility:public\"])\n\n"
         (str/join "\n" (concat (map render-target entries)
                                (for [e entries :when (test-namespace? (:ns-sym e))]
                                  (render-test e)))))))

(defn plan
  "Returns {directory -> BUILD content} for a source root."
  [{:keys [root strip-prefix package-prefix]}]
  (let [root-file (io/file root)
        found (for [f (source-files root-file)
                    :let [form (read-ns-form f)]
                    :when form]
                {:file f
                 :ns-sym (ns-name-of form)
                 :requires (required-namespaces form)
                 :dir (.getParentFile f)})
        ;; Only namespaces in this tree get a label; anything else is a third-party
        ;; dependency the generator has no business guessing at.
        ns->label (into {}
                        (for [{:keys [ns-sym dir]} found]
                          [ns-sym (str "//" package-prefix
                                       (let [rel (relative root-file dir)]
                                         (if (= rel ".") "" (str "/" rel)))
                                       ":" (target-of ns-sym))]))]
    (into {}
          (for [[dir files] (group-by :dir found)]
            [dir (build-file-content {:files (sort-by (comp str :ns-sym) files)
                                      :strip-prefix strip-prefix
                                      :ns->label ns->label})]))))

(defn -main
  [& args]
  (let [opts (into {} (for [a args :let [[_ k v] (re-matches #"--([^=]+)=(.*)" a)] :when k]
                        [(keyword k) v]))
        mode (get opts :mode "write")
        {:keys [root strip-prefix package-prefix]} opts]
    (when-not root
      (binding [*out* *err*]
        (println "usage: --root=DIR --strip-prefix=P --package-prefix=P [--mode=write|check]"))
      (System/exit 2))
    (let [planned (plan {:root root
                         :strip-prefix (or strip-prefix root)
                         :package-prefix (or package-prefix root)})
          stale (for [[dir content] (sort-by (comp str key) planned)
                      :let [target (io/file dir "BUILD.bazel")]
                      :when (not= content (when (.exists target) (slurp target)))]
                  target)]
      (if (= mode "check")
        (if (seq stale)
          (do (binding [*out* *err*]
                (println "These BUILD files are not what the ns forms imply:")
                (doseq [f stale] (println "  " (.getPath ^File f)))
                (println "Run: bazel run //tools/tidy -- --root=..."))
              (System/exit 1))
          (println (format "tidy: %d BUILD files are up to date" (count planned))))
        (do (doseq [[dir content] planned]
              (spit (io/file dir "BUILD.bazel") content))
            (println (format "tidy: wrote %d BUILD files" (count planned)))))
      (shutdown-agents))))
