"""Turns a lockfile into Bazel targets.

Everything interesting happened when the lock was written (`//tools/lock`). This just
fetches what it names and describes it to Bazel — no resolution, no network beyond the
downloads, no `~/.m2`, and the same jars on every machine because each one is pinned by
digest.
"""

_BUILD_HEADER = """\
# Generated by rules_clj from {lock}. Do not edit.
load("@rules_java//java:defs.bzl", "java_import", "java_library")

package(default_visibility = ["//visibility:public"])
"""

def _target(artifact):
    return artifact["target"]

def _clj_deps_repo_impl(repository_ctx):
    lock_path = repository_ctx.path(repository_ctx.attr.lock)
    lock = json.decode(repository_ctx.read(lock_path))

    if lock.get("version") != 1:
        fail("{} is lock format version {}, and this rules_clj understands version 1".format(
            repository_ctx.attr.lock,
            lock.get("version"),
        ))

    repositories = lock.get("repositories", ["https://repo1.maven.org/maven2/"])
    artifacts = lock.get("artifacts", [])

    lines = [_BUILD_HEADER.format(lock = str(repository_ctx.attr.lock))]
    for artifact in artifacts:
        output = "jars/" + artifact["path"]

        # Several URLs, tried in order: the lock records where the project said to look,
        # and a mirror being down should not be the same thing as a broken build.
        repository_ctx.download(
            url = [base + artifact["path"] for base in repositories],
            output = output,
            sha256 = artifact["sha256"],
        )

        deps = [":" + d for d in artifact.get("deps", []) if d != artifact["target"]]
        lines.append("""
# {coordinates}
java_import(
    name = "{target}",
    jars = ["{jar}"],
    deps = {deps},
    tags = ["maven_coordinates={coordinates}"],
)""".format(
            coordinates = artifact["coordinates"],
            target = artifact["target"],
            jar = output,
            deps = repr(deps),
        ))

    # A convenience for the cases where a precise dependency list is not the point —
    # a REPL, a lint pass, a scratch target. Named so that reaching for it is a visible
    # decision rather than a default.
    lines.append("""
java_library(
    name = "all",
    exports = {all},
)""".format(all = repr([":" + _target(a) for a in artifacts])))

    repository_ctx.file("BUILD.bazel", "\n".join(lines) + "\n", executable = False)

clj_deps_repo = repository_rule(
    implementation = _clj_deps_repo_impl,
    doc = "Fetches the jars a lockfile names and exposes them as java_import targets.",
    attrs = {
        "lock": attr.label(
            doc = "The lockfile, as written by //tools/lock.",
            mandatory = True,
            allow_single_file = True,
        ),
    },
)
