"""Fetching GraalVM.

Not through rules_graalvm, and not because that project is unhealthy — it is actively
maintained and its v0.12.0 works on Bazel 9. The blocker is distribution: the newest
release in the Bazel Central Registry is 0.11.1 from January 2024, which does not load on
Bazel 9, and a BCR module may only depend on modules that are themselves in the BCR.
Depending on it would make this ruleset unpublishable; a git_override would make it
unpublishable and root-module-only.

If rules_graalvm >= 0.12.0 lands in the BCR, delete this file and depend on it. Nothing
else assumes ownership of the download.

Checksums come from the .sha256 files GraalVM publishes beside each archive, so pinning a
new version costs a fetch of a few bytes rather than of a few hundred megabytes.
"""

_RELEASES = {
    "21.0.2": {
        "macos-aarch64": "515e3a93acc7e1938daba83eda4272e5495fd302d7cdd99ec7ebf408ed505ab7",
        "macos-x64": "7a8aa93fa45d1721908477abf4732a32637d420ffcb66ada9fb6456440b0d9e1",
        "linux-x64": "b048069aaa3a99b84f5b957b162cc181a32a4330cbc35402766363c5be76ae48",
        "linux-aarch64": "a34be691ce68f0acf4655c7c6c63a9a49ed276a11859d7224fd94fc2f657cd7a",
    },
}

_BUILD = """\
# Generated by rules_clj. Do not edit.
load("@rules_clj//clojure:native_toolchain.bzl", "clj_native_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sdk",
    srcs = glob(["**"], allow_empty = False),
)

clj_native_toolchain(
    name = "graalvm",
    launcher = "{launcher}",
    sdk = ":sdk",
    version = "{version}",
)

toolchain(
    name = "toolchain",
    toolchain = ":graalvm",
    toolchain_type = "@rules_clj//clojure:native_toolchain_type",
)
"""

def _platform(repository_ctx):
    os = repository_ctx.os.name.lower()
    arch = repository_ctx.os.arch.lower()
    if os.startswith("mac"):
        return "macos-aarch64" if arch in ("aarch64", "arm64") else "macos-x64"
    if os.startswith("linux"):
        return "linux-aarch64" if arch in ("aarch64", "arm64") else "linux-x64"
    fail("rules_clj has no GraalVM for {} {}. Native images are POSIX-only here.".format(os, arch))

def _graalvm_repo_impl(repository_ctx):
    version = repository_ctx.attr.version
    if version not in _RELEASES:
        fail("rules_clj does not know GraalVM {}. Known: {}.".format(
            version,
            ", ".join(sorted(_RELEASES)),
        ))

    platform = _platform(repository_ctx)
    archive = "graalvm-community-jdk-{}_{}_bin.tar.gz".format(version, platform)

    repository_ctx.download_and_extract(
        url = "https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-{}/{}".format(version, archive),
        sha256 = _RELEASES[version][platform],
        # The archive wraps everything in one directory, and on macOS that directory
        # contains a Contents/Home bundle rather than the JDK layout directly.
        stripPrefix = "graalvm-community-openjdk-{}+13.1{}".format(
            version,
            "/Contents/Home" if platform.startswith("macos") else "",
        ),
    )

    repository_ctx.file(
        "BUILD.bazel",
        _BUILD.format(launcher = "bin/native-image", version = version),
        executable = False,
    )

graalvm_repo = repository_rule(
    implementation = _graalvm_repo_impl,
    doc = "Downloads a pinned GraalVM for the host platform.",
    attrs = {"version": attr.string(mandatory = True)},
)
