"""Repository rule behind the `clojure` module extension.

Downloads the runtime jars and writes a BUILD file exposing them as a java_import
plus a registered toolchain. Everything is pinned by digest, so the repository is
reproducible and Bazel can cache it like any other.
"""

_BUILD = """\
# Generated by rules_clj. Do not edit.
load("@rules_java//java:defs.bzl", "java_import")
load("@rules_clj//clojure:toolchain.bzl", "clj_toolchain")

package(default_visibility = ["//visibility:public"])

java_import(
    name = "clojure",
    jars = {jars},
)

clj_toolchain(
    name = "runtime",
    runtime = [":clojure"],
    version = "{version}",
)

toolchain(
    name = "toolchain",
    toolchain = ":runtime",
    toolchain_type = "@rules_clj//clojure:toolchain_type",
)
"""

def _clojure_runtime_repo_impl(repository_ctx):
    names = []
    for key in sorted(repository_ctx.attr.jars):
        path, sha256 = repository_ctx.attr.jars[key]
        out = "jars/" + path.rsplit("/", 1)[-1]
        repository_ctx.download(
            url = [base.rstrip("/") + "/" + path for base in repository_ctx.attr.repositories],
            output = out,
            sha256 = sha256,
        )
        names.append(out)

    repository_ctx.file(
        "BUILD.bazel",
        _BUILD.format(
            jars = repr(names),
            version = repository_ctx.attr.version,
        ),
        executable = False,
    )

clojure_runtime_repo = repository_rule(
    implementation = _clojure_runtime_repo_impl,
    doc = "Downloads a pinned Clojure runtime and exposes it as a toolchain.",
    attrs = {
        "version": attr.string(mandatory = True),
        "jars": attr.string_list_dict(mandatory = True),
        "repositories": attr.string_list(mandatory = True),
    },
)
